version: '3.8'
services:
  ceac_stat_tracker:
    build: .
    ports:
      - "5001:5001"
    command: ["gunicorn","main:app", "-w", "5", "-b", "0.0.0.0:5001", "--preload"]
    volumes:
      - "./config.yaml:/myapp/config.yaml"
    networks:
      - my_net
    depends_on:
      - my_mongo
  my_mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - my_net

networks:
  my_net:
    driver: bridge
